### ISSUE TITLE
sailorgram&CPU

### ISSUE THREAD

**Issue by lewadedun** [Dax89/harbour-sailorgram#45] opened 2016-01-25 18:14 UTC
sailorgram uses 50-70% of CPU, if you switch from cellular network to Wi Fi. Or from Wi Fi to cellular network. sailorgram cannot connect to the network, as I understand it.
0.73-beta 14

**Comment by Dax89** [comment] 2016-01-25 18:34
I was figuring out how to reproduce this issue, so I need to switch from mobile to wifi (or viceversa), thanks :)

**Comment by PawelSpoon** [comment] 2016-02-01 05:57
have a similiar issue here now on 2.0.10
when i switch from mobile to wifi, sailorgram can't connect and the menu is not reactive. it s almost impossible to reach exit menu item.
i have to kill from the 'outside'

thanks for all the other new features!

**Comment by Dax89** [comment] 2016-02-16 08:47
This should be fixed in 5e6145b.
Is this issue still present in the latest beta?

**Comment by Dax89** [comment] 2016-02-17 09:37
Seems to be fixed, when I have changed from QNetworkConfigurationManager to Connman

**Closed by Dax89** 2016-02-17 09:37 UTC
Labels: bug
