### ISSUE TITLE
chat list(first page) is not updated

### ISSUE THREAD

**Issue by rollator** [Dax89/harbour-sailorgram#55] opened 2016-02-08 11:46 UTC
Running version 0.79-1, when I chat using the desktop client and have SailorGram running on my Jolla, the chat overview will only update if I **exit** the app and reopen it. This doesen't work if I simply close it, I explicitly need to use the pulldown menu and choose exit

**Comment by Dax89** [comment] 2016-02-08 13:00
Duplicate of #38 (look the conversation)

If you have the daemon enabled the swype doen keeps sailorgram opened in "daemonized" state, that's why I have provided an "Exit" menu :)

**Closed by Dax89** 2016-02-08 13:00 UTC

**Comment by rollator** [comment] 2016-02-08 13:12
so basically the "Exit" menu entry means daemon mode, and if I close the app normally it's shutdown, including the daemon?

**Comment by Dax89** [comment] 2016-02-08 13:30
"Exit" menu is available only when daemon mode is enabled so you can close Sailorgram manually if you want.
It this case, when you do a swype down, only the UI is closed but the client keeps running, clicking the Sailorgram's icon it simply restores the UI.

When daemon mode is disabled the "Exit" menu is not visible and it's closed with a simple swype down, like any other application.
