### ISSUE TITLE
Outgoing messages in secret chat get lost

### ISSUE THREAD

**Issue by mikken** [Dax89/harbour-sailorgram#32] opened 2015-11-04 07:17 UTC
Outgoing messages in secret chat are not seen my companion (using official client). I still see incoming messages from him.
This doesn't start right away but after a while. Not after the first phone sleep, I can't exactly tell when.

**Comment by Dax89** [comment] 2016-01-17 21:35
Duplicate of #38

**Closed by Dax89** 2016-01-17 21:35 UTC
